export const flowers = [
    {
        name: 'evergreen candytuft',
        genus: 'Iberis',
        colors: ['white'],
        petals: 'many',
        edge: ['rounded square'],
        size: 'small',
        shape: 'cluster',
        tree: 'no',
        description: 'Candytuft! What a delightful name for a delightful flower. There is something immensely satisfying (but also frightening) about a cluster of flowers so thick you can\'t see any green. ',
    },
    {
        name: 'scarlet globemallow',
        genus: 'Sphaeralcea',
        colors: ['orange'],
        petals: '5',
        edge: ['notched'],
        size: 'small',
        shape: 'bowl',
        tree: 'no',
        description: 'Not totally scarlet, globular, or mallow-y, this nonetheless pleasant wildflower is also known as "cowboy\'s delight." In late spring you can see large patches of these on drier hills in Utah, whether or not you\'re on horseback.',
    },
    {
        name: 'spreading phlox',
        genus: 'Phlox',
        colors: ['pink'],
        petals: '5',
        edge: ['round', 'rounded square'],
        size: 'small',
        shape: 'flat',
        tree: 'no',
        description: 'These flowers really do spread—you can catch them in enormous patches in shady areas pretty easily, because they can\'t run.',
    },
    {
        name: 'Sarah Bernhardt peony',
        genus: 'Paeonia',
        colors: ['pink'],
        petals: 'many',
        edge: ['notched', 'ruffled'],
        size: 'large',
        shape: 'carnation-like',
        tree: 'no',
        description: 'This enormous, gorgeous flower is like a giant cross between a carnation and a rose.',
    },
    {
        name: 'showy milkweed',
        genus: 'Asclepias',
        colors: ['pink'],
        petals: '5',
        edge: ['pointy'],
        size: 'large',
        shape: 'ball',
        tree: 'no',
        description: 'As far as I can tell, the show this flower\'s putting on is called "Ball of starfish."',
    },
    {
        name: 'tapertip onion',
        genus: 'Allium',
        colors: ['purple'],
        petals: 'many',
        edge: ['pointy'],
        size: 'small',
        shape: 'ball',
        tree: 'no',
        description: 'Also called Hooker\'s onion, this plant is allegedly quite delicious. ',
    },
    {
        name: 'Colorado blue columbine',
        genus: 'Aquilegia',
        colors: ['white'],
        petals: '5',
        edge: ['round'],
        size: 'medium',
        shape: 'star',
        tree: 'no',
        description: 'I\'m not completely sure that I\'ve identified these flowers correctly, but I do know they\'re columbines—you can tell because they have funky little tails coming out the back (called "spurs").',
    },
    {
        name: 'smoothstem blazingstar',
        genus: 'Mentzelia',
        colors: ['yellow'],
        petals: '5',
        edge: ['pointy'],
        size: 'large',
        shape: 'star',
        tree: 'no',
        description: 'This is one of my favorite wildflowers. I love its extravagant name! In early summer, you can find small shrubs in bloom with these highlighter-yellow flowers—act quick, though, because those shrubs will quickly dry out into sad skeletons.',
    },
    {
        name: 'chicory',
        genus: 'Cichorium',
        colors: ['purple'],
        petals: 'many',
        edge: ['notched'],
        size: 'small',
        shape: 'daisy-like',
        tree: 'no',
        description: 'This elusive purple-blue wildflower is a joy to spot! It\'s rather hard to pick off individual flowers, so I might recommend stealing the entire bush.',
    },
    {
        name: 'natal plum',
        genus: 'Carissa',
        colors: ['white'],
        petals: '5',
        edge: ['round'],
        size: 'medium',
        shape: 'star',
        tree: 'no',
        description: 'These elegant stars are a perfect fit for beachside stroll aesthetics.',
    },
    {
        name: 'purple morning glory',
        genus: 'Ipomoea',
        colors: ['purple'],
        petals: '5',
        edge: ['notched'],
        size: 'medium',
        shape: 'trumpet',
        tree: 'no',
        description: 'These are much more eye-catching than the pale pink morning glory that is slowly eating away my hometown.',
    },
    {
        name: 'Texas lantana',
        genus: 'Lantana',
        colors: ['yellow', 'orange'],
        petals: '4',
        edge: ['notched', 'round'],
        size: 'small',
        shape: 'cluster',
        tree: 'no',
        description: 'Lantana is a common choice for city-street flowerpots. I love its colorful clusters, but I\'m still not sure how many petals it has.',
    },
    {
        name: 'lion\'s tail',
        genus: 'Leonotis',
        colors: ['orange'],
        petals: 'many',
        edge: ['fuzzy'],
        size: 'small',
        shape: 'cluster',
        tree: 'no',
        description: 'This flower is also called "wild dagga," which sounds like a useful survival tool.',
    },
    {
        name: 'globe amaranth',
        genus: 'Gomphrena',
        colors: ['pink', 'purple'],
        petals: 'many',
        edge: ['pointy', 'notched'],
        size: 'small',
        shape: 'ball',
        tree: 'no',
        description: 'Wow! These vibrant blooms are extra cool when you look at them close up. At some point I\'ll add support for multiple photos on this site so you can have that experience.',
    },
    {
        name: 'balloon flower',
        genus: 'Platycodon',
        colors: ['purple'],
        petals: '5',
        edge: ['pointy'],
        size: 'large',
        shape: 'star',
        tree: 'no',
        description: 'Strangely, these might be the least balloon-looking flowers I\'ve ever seen.',
    },
    {
        name: 'toad lily',
        genus: 'Tricyrtis',
        colors: ['white', 'purple'],
        petals: '6',
        edge: ['round'],
        size: 'small',
        shape: 'star',
        tree: 'no',
        description: 'I love these funky gems! They are NOTHING like toads!',
    },
    {
        name: 'dahlia',
        genus: 'Dahlia',
        colors: ['pink'],
        petals: 'many',
        edge: ['round', 'notched'],
        size: 'large',
        shape: 'ball',
        tree: 'no',
        description: 'A classy, easily recognizable flower with a name you could comfortably use on your kid.',
    },
    {
        name: 'fire vine',
        genus: 'Ipomoea',
        colors: ['red', 'orange', 'yellow'],
        petals: '5',
        edge: ['none'],
        size: 'small',
        shape: 'stalk',
        tree: 'no',
        description: 'Also known as Spanish flag and firecracker vine, this silly flower brings to mind a pile of happy toucans!',
    },
    {
        name: 'bluemink',
        genus: 'Ageratum',
        colors: ['purple'],
        petals: 'many',
        edge: ['pointy'],
        size: 'small',
        shape: 'cluster',
        tree: 'no',
        description: 'I\'m a huge fan of this flower\'s name, which seems like it came from a lazy guy trying to get out of his hunting duties back in the days when the color purple hadn\'t been invented yet. "I\'m gonna go look for blue mink!" or something. You can also call it "flossflower."',
    },
    {
        name: 'crested cockscomb',
        genus: 'Celosia',
        colors: ['red', 'pink'],
        petals: 'many',
        edge: ['ruffled'],
        size: 'large',
        shape: 'ruffle',
        tree: 'no',
        description: 'I\'m a little upset by this one because it\'s hard to categorize and looks way too much like a brain.',
    },
    {
        name: 'white campion',
        genus: 'Silene',
        colors: ['white'],
        petals: '5',
        edge: ['notched'],
        size: 'small',
        shape: 'gourd',
        tree: 'no',
        description: 'When I look at these I imagine the taste of wintermelon, a vegetable I hate.',
    },
    {
        name: 'lanceleaf liveforever',
        genus: 'dudleya',
        colors: ['red', 'orange', 'yellow'],
        petals: '6',
        edge: ['pointy'],
        size: 'small',
        shape: 'stalk',
        tree: 'no',
        description: 'I think everything to know about this flower is included in its absurdly original name, the most flagrant offender I\'ve seen of flower-namer-people Just Making Up Words since "smoothstem blazingstar."',
    },
    {
        name: 'seafoam statice',
        genus: 'Limonium',
        colors: ['purple', 'white'],
        petals: '5',
        edge: ['round', 'notched'],
        size: 'small',
        shape: 'cluster',
        tree: 'no',
        description: 'A lovely cluster also known as Perez\'s sea lavender—take a moment to spot the intermittent little white flowers!',
    },
    {
        name: 'verbena',
        genus: 'Verbena',
        colors: ['purple'],
        petals: '5',
        edge: ['notched'],
        size: 'small',
        shape: 'cluster',
        tree: 'no',
        description: 'It\'s a ball of flowers, hiding a fuzzy little secret...',
    },
    {
        name: 'painter\'s palette',
        genus: 'Anthurium',
        colors: ['red', 'yellow'],
        petals: '2',
        edge: ['fused'],
        size: 'large',
        shape: 'leaf',
        tree: 'no',
        description: 'A leaf disguised as a flower, this thing is also called flamingo flower, oilcloth flower, and laceleaf.',
    },
    {
        name: 'Texas bluebonnet',
        genus: 'Lupinus',
        colors: ['purple', 'yellow', 'white'],
        petals: 'many',
        edge: ['round'],
        size: 'large',
        shape: 'stalk',
        tree: 'no',
        description: 'This photo was taken just off of a highway in Texas in the springtime, just like Lady Bird Johnson wanted. ',
    },
    {
        name: 'evening primrose',
        genus: 'Oenothera',
        colors: ['white', 'pink'],
        petals: '4',
        edge: ['notched'],
        size: 'large',
        shape: 'bag',
        tree: 'no',
        description: 'I classify the shape of this flower as "bag" because no flower has looked more like a discarded plastic bag to me. These flowers have no integrity—this photo was taken at 8AM, a far cry from "evening."',
    },
    {
        name: 'sego lily',
        genus: 'Calochortus',
        colors: ['white'],
        petals: '3',
        edge: ['pointy'],
        size: 'small',
        shape: 'cup',
        tree: 'no',
        description: 'Utah\'s state flower is much smaller than you might expect. Look closely off-trail in late spring to spot it, and be careful up close—sego lilies make good homes for spiders and other yucky bugs.',
    },
    {
        name: 'spider milkweed',
        genus: 'Asclepias',
        colors: ['green', 'purple'],
        petals: '5',
        edge: ['pointy'],
        size: 'large',
        shape: 'ball',
        tree: 'no',
        description: 'Also called antelope horns milkweed, this flower is absolutely bonkers.',
    },
    {
        name: 'narrow-leaf penstemon',
        genus: 'Penstemon',
        colors: ['purple'],
        petals: '5',
        edge: ['round', 'notched'],
        size: 'small',
        shape: 'stalk',
        tree: 'no',
        description: 'You can also call this plant toax-flax beardtongue—I\'m not sure why.',
    },
    {
        name: 'thistle',
        genus: 'Cirsium',
        colors: ['purple'],
        petals: 'many',
        edge: ['pointy'],
        size: 'medium',
        shape: 'gourd',
        tree: 'no',
        description: 'This thistle is hosting a soldier beetle friend!',
    },
    {
        name: 'Lotus japonicus',
        genus: 'Lotus',
        colors: ['yellow'],
        petals: '2',
        edge: ['round', 'pointy'],
        size: 'small',
        shape: 'cluster',
        tree: 'no',
        description: 'To my dismay, this cutie has no common name yet. Sunshine horseshoeflower, anyone?',
    },
    {
        name: 'musk-mallow',
        genus: 'Malva',
        colors: ['pink'],
        petals: '5',
        edge: ['notched'],
        size: 'small',
        shape: 'bowl',
        tree: 'no',
        description: 'After looking at all these flowers called "mallow," I\'m really curious who was responsible for naming marshmallows.',
    },
    {
        name: 'Queen Anne\'s lace',
        genus: 'Daucus',
        colors: ['white'],
        petals: 'many',
        edge: ['round'],
        size: 'large',
        shape: 'cluster',
        tree: 'no',
        description: 'Alternative names for this plant include wild carrot and bird\'s nest, neither of which evoke as fun of an image as Queen Anne\'s lace. If you look closely you can see a red dot in the center of the flower cluster that represents blood from Queen Anne pricking her finger while making the lace, which is pretty disgusting if you ask me.',
    },
    {
        name: 'bird vetch',
        genus: 'Vicia',
        colors: ['purple'],
        petals: '2',
        edge: ['round', 'fused'],
        size: 'small',
        shape: 'stalk',
        tree: 'no',
        description: 'This flower has a lot of other arguably descriptive common names such as tufted vetch, boreal vetch, cow vetch, and blue vetch. The only thing the flower community seems to have agreed upon is that it\'s vetch!',
    },
    {
        name: 'red clover',
        genus: 'Trifolium',
        colors: ['pink'],
        petals: 'many',
        edge: ['round', 'pointy'],
        size: 'small',
        shape: 'ball',
        tree: 'no',
        description: ':)',
    },
    {
        name: 'crownvetch',
        genus: 'Securigera',
        colors: ['pink'],
        petals: 'many',
        edge: ['round'],
        size: 'small',
        shape: 'cluster',
        tree: 'no',
        description: 'I would like to talk to the person who came up with the name vetch, because it sounds much too pointy for flowers!',
    },
    {
        name: 'buttonbush',
        genus: 'Cephalanthus',
        colors: ['white', 'brown'],
        petals: 'many',
        edge: ['pointy'],
        size: 'small',
        shape: 'ball',
        tree: 'no',
        description: 'Also called honey-bells, this flower was too spiky for this bee to linger long.',
    },
    {
        name: 'garden nasturtium',
        genus: 'Tropaeolum',
        colors: ['orange'],
        petals: '5',
        edge: ['ruffled', 'round', 'notched'],
        size: 'medium',
        shape: 'cup',
        tree: 'no',
        description: 'Nasturtium is an appropriate name for a flower that is beautiful but looks like it would gossip if it could.',
    },
    {
        name: 'everlasting flower',
        genus: 'Helichrysum',
        colors: ['pink', 'white'],
        petals: 'many',
        edge: ['round'],
        size: 'small',
        shape: 'daisy-like',
        tree: 'no',
        description: 'I love the shiny mysteriousness of this flower! We may never know what it\'s hiding in its heart.',
    },
    {
        name: 'trumpet vine',
        genus: 'Campsis',
        colors: ['orange'],
        petals: '5',
        edge: ['round', 'notched'],
        size: 'small',
        shape: 'trumpet',
        tree: 'no',
        description: 'The alternative name for this flower, "cow itch vine," raises a lot of questions.',
    },
    {
        name: 'desert wirelettuce',
        genus: 'Stephanomeria',
        colors: ['pink'],
        petals: '5',
        edge: ['notched'],
        size: 'small',
        shape: 'star',
        tree: 'no',
        description: 'I had a hard time identifying this flower and may have done it wrong—I\'ve thought before that it\'s skeletonplant. It\'s got impressive spork petals.',
    },
    {
        name: 'narrowleaf four o\'clock',
        genus: 'Mirabilis',
        colors: ['white', 'pink'],
        petals: '5',
        edge: ['notched'],
        size: 'small',
        shape: 'trumpet',
        tree: 'no',
        description: 'Four o\'clocks were thusly named because they open at four o\'clock, and I guess the people who named them had never been up at 7AM like I have.',
    },
    {
        name: 'Egyptian starcluster',
        genus: 'Pentas',
        colors: ['pink'],
        petals: '5',
        edge: ['pointy'],
        size: 'small',
        shape: 'cluster',
        tree: 'no',
        description: 'The color of these flowers does not evoke Egypt for me. Instead, I\'m thinking about a shirt I thought was cool in 2014...',
    },
    {
        name: 'African daisy',
        genus: 'Dimorphotheca',
        colors: ['white', 'pink'],
        petals: 'many',
        edge: ['spoon'],
        size: 'medium',
        shape: 'daisy-like',
        tree: 'no',
        description: 'These are some of the mesmerizingest flowers I\'ve spotted. Also called Cape marguerite, their petals look like, but cannot be used as, spoons.',
    },
    {
        name: 'nemesia',
        genus: 'Nemesia',
        colors: ['red', 'pink', 'yellow'],
        petals: 'many',
        edge: ['round', 'notched'],
        size: 'medium',
        shape: 'cluster',
        tree: 'no',
        description: 'Tutu designers could learn a thing or two from these flowers!',
    },
    {
        name: 'spider flower',
        genus: 'Grevilla',
        colors: ['red', 'green'],
        petals: 'many',
        edge: ['round', 'pointy'],
        size: 'small',
        shape: 'ball',
        tree: 'no',
        description: 'I\'d have named this anything other than spider flower.',
    },
    {
        name: 'blue felicia',
        genus: 'Felicia',
        colors: ['purple'],
        petals: 'many',
        edge: ['round'],
        size: 'small',
        shape: 'daisy-like',
        tree: 'no',
        description: 'This flower is another relic from the days before purple was invented.',
    },
    {
        name: 'tiger-eye pansy',
        genus: 'Viola',
        colors: ['yellow', 'brown'],
        petals: '5',
        edge: ['round', 'notched'],
        size: 'small',
        shape: 'flat',
        tree: 'no',
        description: 'According to Wikipedia, pansies are hybrid creations, like donkeys.',
    },
    {
        name: 'anemone',
        genus: 'Anemone',
        colors: ['white', 'pink', 'red', 'purple'],
        petals: 'many',
        edge: ['round', 'rounded square'],
        size: 'large',
        shape: 'bowl',
        tree: 'no',
        description: 'Sea anemones were named after anemone flowers because both are colorful, which is hilarious because I can think of plenty of flowers that are just as colorful AND easier to spell.',
    },
    {
        name: 'common stork\'s-bill',
        genus: 'Erodium',
        colors: ['pink'],
        petals: '5',
        edge: ['round', 'rounded square'],
        size: 'small',
        shape: 'star',
        tree: 'no',
        description: 'Also called redstem filaree and pinweed, this flower is known as stork\'s bill because it\'s got sharp, beak-looking seed-pods.',
    },
    {
        name: 'birdeye speedwell',
        genus: 'Veronica',
        colors: ['blue'],
        petals: '4',
        edge: ['round'],
        size: 'small',
        shape: 'bowl',
        tree: 'no',
        description: 'Other names for this plant include winter speedwell and bird\'s-eye. ',
    },
    {
        name: 'dandelion',
        genus: 'Taraxacum',
        colors: ['yellow'],
        petals: 'many',
        edge: ['notched'],
        size: 'medium',
        shape: 'circle',
        tree: 'no',
        description: 'This one has a red soldier bug on it!',
    },
    {
        name: 'grape hyacinth',
        genus: 'Muscari',
        colors: ['purple'],
        petals: '1',
        edge: ['round', 'notched'],
        size: 'small',
        shape: 'stalk',
        tree: 'no',
        description: 'Neither hyacinth nor grapes.',
    },
    {
        name: 'apple',
        genus: 'Malus',
        colors: ['white'],
        petals: '5',
        edge: ['round', 'ruffled'],
        size: 'small',
        shape: 'bowl',
        tree: 'yes',
        description: 'I adore the smell of this flower! Much better than the fishy smell of the Bradford pear.',
    },
    {
        name: 'grass lily',
        genus: 'Ornithogalum',
        colors: ['white'],
        petals: '6',
        edge: ['pointy'],
        size: 'small',
        shape: 'cup',
        tree: 'no',
        description: 'Also called nap-at-noon and eleven-o\'clock lady, these little lilies were a stellar surprise to find on the side of a trail. ',
    },
    {
        name: 'Japanese wisteria',
        genus: 'Wisteria',
        colors: ['white', 'purple'],
        petals: '2',
        edge: ['fused', 'pointy', 'round'],
        size: 'large',
        shape: 'stalk',
        tree: 'no',
        description: 'I\'m not actually sure if this one is a tree.',
    },
    {
        name: 'Kanzan cherry',
        genus: 'Prunus',
        colors: ['pink'],
        petals: 'many',
        edge: ['notched', 'ruffled'],
        size: 'medium',
        shape: 'carnation-like',
        tree: 'yes',
        description: 'In my humble opinion, the best color of tree is pink!',
    },
    {
        name: 'Chinese redbud',
        genus: 'Cercis',
        colors: ['pink'],
        petals: '5',
        edge: ['round', 'fused'],
        size: 'small',
        shape: 'cluster',
        tree: 'yes',
        description: 'With fiercely magenta flowers, these trees make a powerful contribution to any springtime neighborhood.',
    },
    {
        name: 'lilac',
        genus: 'Syringa',
        colors: ['white', 'pink'],
        petals: '4',
        edge: ['round'],
        size: 'small',
        shape: 'stalk',
        tree: 'no',
        description: 'An unassuming shrub in most seasons, the lilac is a wonderful surprise in the spring.',
    },
    ];
    